WELCOME_MESSAGE:
  - "&7&m-------------------------------------------------"
  - "  &fWelcome to &eSpigotMC"
  - ""
  - "  ● &eWebsite: &fhttps://example.com"
  - "  ● &eDiscord: &fhttps://example.com"
  - "  ● &eStore: &fhttps://example.com"
  - "  ● &eTwitter: &fhttps://example.com"
  - "&7&m-------------------------------------------------"